driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: install
    run_list: test::install
  - name: package
    run_list: test::package
  - name: service
    run_list: test::service
