driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.8
  - name: debian-9.0
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: install
    run_list: test::install
  - name: package
    run_list: test::package
  - name: service
    run_list: test::service
    # these platforms don't have systemd as the default init system
    excludes:
      - centos-6.9
      - debian-7.11
      - ubuntu-14.04
  - name: sup
    run_list: test::sup
    # these platforms don't have systemd as the default init system
    excludes:
      - centos-6.9
      - debian-7.11
      - ubuntu-14.04
